select * from revenue_data limit 10;

-- Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from revenue_data
group by gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount?

--select AVG(purchase_amount) from revenue_data;
select age_group, customer_id, purchase_amount
from revenue_data
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from revenue_data);

--Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average Product Rating"
from revenue_data
group by item_purchased
order by AVG(review_rating) desc
limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

select shipping_type, round(avg(purchase_amount::numeric),2)
from revenue_data
where shipping_type in ('Standard', 'Express')
group by shipping_type;


--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subs and non subs 
select subscription_status, count(customer_id) as total_customer, 
round(avg(purchase_amount::numeric),2) as avg_spent,
round(sum(purchase_amount::numeric),2) as total_revenue
from revenue_data
group by subscription_status
order by total_revenue, avg_spent desc;


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, 
round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from revenue_data
group by item_purchased
order by discount_rate desc
limit 5;


--Q7. Segment customers into New, Returning, and Loyal based on their 
--total number of previous purchases, and show the count of each segment. 
with customer_type as (
select customer_id, previous_purchases,
case
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from revenue_data
)

select customer_segment, count(*) as "number_of_customers"
from customer_type
group by customer_segment;


--Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT category, item_purchased, COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM revenue_data
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

 
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) AS repeat_buyers
FROM revenue_data
WHERE previous_purchases > 5
GROUP BY subscription_status;


--Q10. What is the revenue contribution of each age group?
SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM revenue_data
GROUP BY age_group
ORDER BY total_revenue desc;
